extensions:
  #bearertokenauth:
    #filename: /conf/edge-token
  basicauth/client:
    client_auth:
      username: xxxx
      password: xxxx
  file_storage:
    directory: /otc
    timeout: 10s
receivers:
  journald:
    directory: /var/log/journal/
    units:
      - ssh
      - kube-apiserver
      - ovn-kubernetes
      - crio
    priority: info
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:12334
  prometheus:
    config:
      scrape_configs:
      - job_name: 'pmproxy-rhedge'
        scrape_interval: 5s
        static_configs:
        - targets: ['0.0.0.0:44322'] # instrumented app endpoint

processors:
  batch:
  memory_limiter:
    check_interval: 5s
    limit_percentage: 95
    spike_limit_percentage: 25
exporters:
  otlphttp:
    endpoint: https://otlp-https.apps.open-svc-sts.k1wl.p1.openshiftapps.com
    auth:
      authenticator: basicauth/client
    headers:
      x-scope-orgid: "infrastructure"
    tls:
      insecure: false
      ca_file: /conf/ca/ca.crt
    sending_queue:
      storage: file_storage
  logging:
    verbosity: detailed
service:
  extensions: [file_storage,basicauth/client]
  telemetry:
    metrics:
      level: detailed
      address: 0.0.0.0:8887
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [otlphttp]
    traces:
      receivers: [otlp]
      exporters: [otlphttp]
    logs:
      receivers: [journald,otlp]
      exporters: [otlphttp]
