---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-reader
rules:
- apiGroups:
  - loki.grafana.com
  - tempo.grafana.com
  resourceNames:
  - logs
  - traces
  resources:
  - dev
  - prod
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-reader-binding
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:authenticated
