apiVersion: v1
kind: ServiceAccount
metadata:
  name: microshift-access
  namespace: monitoring
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jaeger-operator-with-auth-delegator
  namespace: openshift-operators
subjects:
- kind: ServiceAccount
  name: jaeger-operator
  namespace: openshift-operators
roleRef:
  kind: ClusterRole
  name: system:auth-delegator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: microshift-access
subjects:
- kind: ServiceAccount
  name: microshift-access
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: cluster-reader
  apiGroup: rbac.authorization.k8s.io

