# This file is meant to be applied with an OpenShift cluster
# This creates a configmap with the CA for TLS and an OpenTelemetryCollector CR
# Apply this if running the OpenTelemetry Operator to configure OpenTelemetryCollector in OCP
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  name: otelcol-cabundle
  namespace: monitoring
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otelcol
  namespace: monitoring
spec:
  config: |
    extensions:
      basicauth:
        htpasswd:
          inline: |
            sally:password1234

    receivers:
      otlp:
        protocols:
          http:

    processors:
      batch:

    exporters:
      logging:
        verbosity: detailed
      jaeger:
        # monitoring is the name of the namespace, oteljaeger is jaeger name, modify accordingly
        endpoint: oteljaeger-collector-headless.monitoring.svc:14250
        tls:
          ca_file: "/etc/pki/ca-trust/source/service-ca/service-ca.crt"

    service:
      extensions: [basicauth]
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [jaeger,logging]

  mode: deployment
  resources: {}
  targetAllocator: {}
  volumeMounts:
  - mountPath: /etc/pki/ca-trust/source/service-ca
    name: cabundle-volume
  volumes:
  - configMap:
      name: otelcol-cabundle
    name: cabundle-volume
