kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: otelcol
  namespace: monitoring
spec:
  to:
    kind: Service
    name: otelcol-collector
    weight: 100
  port:
    targetPort: 4318
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    wildcardPolicy: None
