apiVersion: v1
kind: Secret
metadata:
  name: edge-sa-token
  namespace: thanos
  annotations:
    kubernetes.io/service-account.name: edge
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: thanos-sa-token
  namespace: thanos
  annotations:
    kubernetes.io/service-account.name: thanos-receive
type: kubernetes.io/service-account-token
