apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: summit-grafana
  namespace: summitdemo
spec:
  baseImage: docker.io/grafana/grafana:8.5.5
  config:
    auth:
      disable_signout_menu: true
    auth.anonymous:
      enabled: true
    log:
      level: warn
      mode: console
    security:
      admin_password: summit
      admin_user: summit
  dashboardLabelSelector:
  - matchExpressions:
    - key: app
      operator: In
      values:
      - grafana
  ingress:
    enabled: true
status: {}
