apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  labels:
    otel: collect
  name: otelcol
  namespace: kepler
spec:
  config: |
    extensions:
      basicauth/client:
        client_auth:
          username: xxxxx
          password: xxxxx
      file_storage:
        directory: ./otc
        timeout: 10s
    receivers:
      otlp:
        protocols:
          http:
          grpc:
            include_metadata: true
      prometheus:
        config:
          scrape_configs:
          - job_name: 'kepler'
            scrape_interval: 5s
            static_configs:
            - targets: ['0.0.0.0:9102'] # instrumented app endpoint
          - job_name: 'otel-collector'
            scrape_interval: 10s
            static_configs:
            - targets: ['localhost:8888']
          - job_name: 'crio'
            scrape_interval: 10s
            static_configs:
            - targets: ['0.0.0.0:9537']
    processors:
      batch:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 95
        spike_limit_percentage: 25
    exporters:
      otlphttp:
        # endpoint: https://OCP_ROUTE_OTELCOL
        endpoint: https://otlp-https.apps.open-svc-sts.k1wl.p1.openshiftapps.com
        auth:
          authenticator: basicauth/client
        tls:
          insecure: false
          ca_file: /conf/ca/ca.crt
        sending_queue:
          storage: file_storage
      logging:
        verbosity: detailed
    service:
      extensions: [basicauth/client,file_storage]
      pipelines:
        metrics:
          receivers: [otlp,prometheus]
          exporters: [otlphttp]
        traces:
          receivers: [otlp]
          exporters: [otlphttp,logging]
        logs:
          receivers: [otlp]
          exporters: [otlphttp]
  hostNetwork: true
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.74.0
  ingress:
    route: {}
  mode: sidecar
  replicas: 1
  resources: {}
  securityContext:
    privileged: true
  serviceAccount: kepler-sa
  targetAllocator:
    prometheusCR: {}
  upgradeStrategy: automatic
  volumeMounts:
  - mountPath: /conf/ca
    name: client-ca
  - mountPath: /otc
    name: file-storage
  - mountPath: /etc/pki/ca-trust/source/service-ca
    name: cabundle-volume
  volumes:
  - configMap:
      name: otelcol-cabundle
    name: cabundle-volume
  - configMap:
      name: client-ca
    name: client-ca
  - hostPath:
      path: /var/lib/microshift/otel
      type: DirectoryOrCreate
    name: file-storage
status: {}
