---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otelcol
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kepler-exporter
data:
  otel-collector-config: |
    extensions:
      # don't use in production
      # using here bc bearertokenauth isn't working
      basicauth/client:
        client_auth:
          username: sally
          password: password1234
    receivers:
      otlp:
        protocols:
          http:
          grpc:
            max_recv_msg_size_mib: 999999999
      prometheus:
        config:
          scrape_configs:
          - job_name: 'otel-collector'
            scrape_interval: 5s
            static_configs:
             - targets: ['<KEPLER_CLUSTER_IP>:9102']
    processors:
      memory_limiter:
        check_interval: 1s
        limit_mib: 2000
        spike_limit_mib: 400
      batch:
    exporters:
      otlphttp:
        endpoint: https://otlphttp.apps.ci-ln-rx38hi2-76ef8.aws-2.ci.openshift.org # otel-collector service route from OCP, port 4318
        auth:
          authenticator: basicauth/client
        tls:
          insecure: false
          # from client-ca configmap
          # extract the root CA from OCP and scp to MicroShift
          # oc extract cm/kube-root-ca.crt -n openshift-config --confirm
          # (in MicroShift) oc create configmap -n otelcol client-ca --from-file ca.crt
          ca_file: /ca/client-ca
      logging:
        loglevel: debug
      prometheusremotewrite:
        endpoint: https://<USERNAME>:<PASSWORD>@<PROMENDPOINTURL>
        # for me looks something like:
        #endpoint: https://64777:eyJrIjoxxxxxxxxxxxxxxx@prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
      jaeger:
        endpoint: "0.0.0.0:14250" # Jaeger service, forwarded from host
        tls:
          insecure: true
    service:
      extensions: [basicauth/client]
      telemetry:
        metrics:
          level: detailed
          address: 0.0.0.0:9999
      pipelines:
        extensions: [basicauth/client]
        metrics:
          receivers: [prometheus]
          processors: [batch]
          exporters: [logging,prometheusremotewrite,otlphttp]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging,jaeger,otlphttp]
