name = "rhde-microshift"
description = "RHDE Microshift Image"
version = "1.0.0"
modules = []
groups = []

[[packages]]
name = "vim"
version = "*"

[[packages]]
name = "kernel-devel-4.18.0-425.19.2.el8_7.x86_64"
version = "*"

[[packages]]
name = "cloud-utils-growpart"
version = "*"

[[packages]]
name = "pcp-zeroconf"
version = "*"

[[packages]]
name = "redis"
version = "*"

[[packages]]
name = "cyrus-sasl-scram"
version = "*"

[[packages]]
name = "cyrus-sasl-lib"
version = "*"

[[packages]]
name = "microshift"
version = "4.12.0*"

[[packages]]
name = "pcp-pmda-bpftrace"
version = "*"

[[packages]]
name = "pcp-pmda-bcc"
version = "*"

[[packages]]
name = "openshift-clients"
version = "*"

[[packages]]
name = "git"
version = "*"

[[packages]]
name = "iputils"
version = "*"

[[packages]]
name = "bind-utils"
version = "*"

[[packages]]
name = "net-tools"
version = "*"

[[packages]]
name = "iotop"
version = "*"

[[packages]]
name = "redhat-release"
version = "*"

[customizations]

[customizations.services]
enabled = ["microshift"]
