---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otelcol
  namespace: otelcol
  labels:
    otel: collect
data:
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          http:
          grpc:
      prometheus:
        config:
          scrape_configs:
          - job_name: 'otel-collector'
            scrape_interval: 5s
            static_configs:
             # any target listed must have a networkpolicy allowing opentelemetry collector access to metrics
            - targets: ['10.42.0.118:9102'] # application metrics endpoint
    processors:
      memory_limiter:
        check_interval: 1s
        limit_mib: 2000
        spike_limit_mib: 400
      batch:
    exporters:
      logging:
        verbosity: detailed
      prometheusremotewrite:
        endpoint: https://<USERNAME>:<PASSWORD>@<PROMENDPOINTURL>
        # for me looks something like: 
        # endpoint: https://64777:eyJrIjoxxxxxxxxxxxxxxx@prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
      jaeger:
        endpoint: "localhost:14250" # Jaeger service port-forwarded from remote (local) machine
        tls:
          insecure: true
    service:
      telemetry:
        metrics:
          level: detailed
          address: 0.0.0.0:9999
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [batch]
          exporters: [prometheusremotewrite, logging]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [jaeger]
