---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  name: otelcol-cabundle
  namespace: observability
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otelcol
  namespace: observability
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    otel: collect
  name: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      otel: collect
  template:
    metadata:
      labels:
        otel: collect
    spec:
      serviceAccountName: otelcol 
      hostNetwork: true # this is only to access hostNetwork Jaeger service
      serviceAccount: otelcol 
      securityContext:
        privileged: true
      volumes:
      - configMap:
          name: otelcol
        name: otelconfig
      - configMap:
          name: client-ca
        name: client-ca
      - configMap:
          name: edge-token
        name: edge-token
      - configMap:
          name: otelcol-cabundle
        name: cabundle-volume
      containers:
      - name: otel-collector
        imagePullPolicy: IfNotPresent
        args:
          - "--config=/conf/config/otelconfig.yaml"
        image: quay.io/sallyom/ubi8-otelcolcontrib:latest
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 4317 # Default endpoint for OpenTelemetry receiver.
        - containerPort: 4318 # Default endpoint for OpenTelemetry receiver.
        - containerPort: 9999
        volumeMounts:
        - mountPath: /conf/ca
          name: client-ca
        - mountPath: /conf/edge-token
          name: edge-token
        - mountPath: /conf/config
          name: otelconfig
        - mountPath: /etc/pki/ca-trust/source/service-ca
          name: cabundle-volume
---
apiVersion: v1
kind: Service
metadata:
  labels:
    otel: collect
  name: otel-collector
spec:
  ports:
  - name: otlp
    port: 4317
    protocol: TCP
  - name: otlphttp
    port: 4318
    protocol: TCP
  selector:
    otel: collect
  type: ClusterIP
