apiVersion: v1
kind: ServiceAccount
metadata:
  name: otelcol
  namespace: otelcol
---
# This file is meant to be applied with an OpenShift cluster
# This creates a configmap with the CA for TLS
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  name: otelcol-cabundle
  namespace: otelcol
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    otel: collect
  name: otel-collector
  namespace: otelcol
spec:
  replicas: 1
  selector:
    matchLabels:
      otel: collect
  template:
    metadata:
      labels:
        otel: collect
    spec:
      serviceAccountName: otelcol 
      hostNetwork: true # this is only to access hostNetwork Jaeger service
      serviceAccount: otelcol 
      securityContext:
        privileged: true
      volumes:
      - configMap:
          name: otelcol
          items:
            - key: otel-collector-config
              path: otel-collector-config.yaml
        name: otel-collector-config
      - configMap:
          name: otelcol-cabundle
        name: cabundle-volume
      containers:
      - name: otel-collector
        imagePullPolicy: IfNotPresent
        args:
          - "--config=/conf/otel-collector-config.yaml"
        image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.64.1
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 500Mi
        ports:
        - containerPort: 4317 # Default endpoint for OpenTelemetry receiver.
        - containerPort: 9999
        volumeMounts:
        - mountPath: /conf
          name: otel-collector-config
        - mountPath: /etc/pki/ca-trust/source/service-ca
          name: cabundle-volume
---
apiVersion: v1
kind: Service
metadata:
  labels:
    otel: collect
  name: otel-collector
  namespace: otelcol
spec:
  ports:
  - name: otlp
    port: 4317
    protocol: TCP
  selector:
    otel: collect
  type: ClusterIP
