spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: kepler-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: kepler-exporter
    spec:
      containers:
      - name: otel-collector
        args:
          - "--config=/conf/otel-collector-config.yaml"
        image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.64.1
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 500Mi
        securityContext:
          privileged: true
        ports:
        #- containerPort: 4317 # Default endpoint for OpenTelemetry receiver.
        #- containerPort: 14268 # Default endpoint for Jaeger receiver.
        - containerPort: 8888  # Default endpoint for querying metrics.
        #env:
        #- name: JAEGER_AGENT_HOST
        #  valueFrom:
        #    fieldRef:
        #      fieldPath: status.hostIP
        volumeMounts:
        - mountPath: /conf
          name: otel-collector-config
        - mountPath: /etc/pki/ca-trust/source/service-ca
          name: cabundle-volume
      volumes:
      - configMap:
          name: otelcol-cabundle
        name: cabundle-volume
      - configMap:
          name: otelcol
          items:
            - key: otel-collector-config
              path: otel-collector-config.yaml
        name: otel-collector-config
