extensions:
  bearertokenauth:
    filename: /conf/edge-token
  file_storage:
    directory: /otc
    timeout: 10s
receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'pmproxy-rhedge'
        scrape_interval: 5s
        static_configs:
        - targets: ['127.0.0.1:44322'] # instrumented app endpoint

processors:
  batch:
  memory_limiter:
    check_interval: 5s
    limit_percentage: 95
    spike_limit_percentage: 25
exporters:
  prometheusremotewrite/ocp:
    endpoint: https://thanos-receive-thanos.apps.open-svc-sts.k1wl.p1.openshiftapps.com/api/v1/receive
    auth:
      authenticator: bearertokenauth
    tls:
      insecure: false
      ca_file: /conf/ca.crt
  logging:
    verbosity: detailed
service:
  extensions: [file_storage,bearertokenauth]
  telemetry:
    metrics:
      level: detailed
      address: 0.0.0.0:8887
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [prometheusremotewrite/ocp]
